import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#101722' },
  content: { padding: 22, paddingBottom: 44, gap: 14 },
  eyebrow: { color: '#92B9CB', fontSize: 10, letterSpacing: 2 },
  title: { color: '#F5F7FA', fontSize: 28, fontWeight: '800' },
  subtitle: { color: '#B3BECD', fontSize: 14 },
  notice: { backgroundColor: '#20303D', borderRadius: 10, padding: 12 },
  noticeText: { color: '#B6D3E3', fontSize: 12, lineHeight: 18 },
  tabs: { flexDirection: 'row', padding: 5, backgroundColor: '#1B2533', borderRadius: 14, marginVertical: 8 },
  tab: { flex: 1, paddingVertical: 14, alignItems: 'center', borderRadius: 10 },
  activeTab: { backgroundColor: '#D7BB7B' },
  tabText: { color: '#9EAEC1', fontWeight: '700', fontSize: 14 },
  activeTabText: { color: '#242015' },
  sectionHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  heading: { color: '#F1F5F9', fontSize: 18, fontWeight: '700' },
  muted: { color: '#A3B1C3', fontSize: 13, lineHeight: 20 },
  cardRow: { flexDirection: 'row', gap: 16, padding: 14, backgroundColor: '#1A2432', borderRadius: 15, borderWidth: 1, borderColor: '#2D3A4D', alignItems: 'center' },
  selectedCard: { borderWidth: 3, backgroundColor: '#29303A' },
  maxLevelCard: { overflow: 'visible' },
  imageWrap: { width: 64, height: 90, position: 'relative' },
  cardImage: { width: '100%', height: '100%', resizeMode: 'contain' },
  rarityBadge: { position: 'absolute', top: 2, right: 2, paddingHorizontal: 2, paddingVertical: 1, borderRadius: 3 },
  rarityText: { color: '#20242B', fontSize: 6, fontWeight: '800' },
  levelBadge: { position: 'absolute', left: 2, bottom: 2, backgroundColor: 'rgba(8, 12, 20, 0.84)', borderColor: '#EAC681', borderWidth: 0.5, borderRadius: 3, paddingHorizontal: 2, paddingVertical: 1 },
  level: { color: '#F5D390', fontSize: 6, fontWeight: '800' },
  cardInfo: { flex: 1, gap: 5 },
  cardName: { color: '#F1F5F9', fontWeight: '700', fontSize: 15 },
  cardValue: { color: '#9DDCEC', fontSize: 15, fontWeight: '700' },
  checkbox: { width: 26, height: 26, borderRadius: 8, borderWidth: 1, borderColor: '#617187', alignItems: 'center', justifyContent: 'center' },
  checked: { backgroundColor: '#D7BB7B', borderColor: '#D7BB7B' },
  checkText: { color: '#242015', fontSize: 17, fontWeight: '800' },
  summary: { backgroundColor: '#1B3040', borderRadius: 16, padding: 22, gap: 10, marginTop: 6 },
  total: { color: '#B5E9F5', fontSize: 30, fontWeight: '800' },
  unit: { color: '#B7C9D9', fontSize: 15 },
  summaryNote: { color: '#A7BCCB', fontSize: 12, lineHeight: 18 },
  button: { backgroundColor: '#D7BB7B', borderRadius: 14, padding: 18, alignItems: 'center', marginTop: 6 },
  buttonText: { color: '#242015', fontSize: 16, fontWeight: '800' },
  disabled: { opacity: 0.35 },
  valueTable: { backgroundColor: '#1A2432', padding: 16, borderRadius: 15, marginTop: 12, gap: 12 },
  tableRow: { flexDirection: 'row', paddingVertical: 6, borderBottomWidth: 1, borderBottomColor: '#2A3648' },
  tableGrade: { flex: 1, color: '#C6D0DD', fontSize: 12 },
  tableNumber: { flex: 1, color: '#C6D0DD', fontSize: 12, textAlign: 'right' },
  tableNote: { color: '#889BB0', fontSize: 11 },
  rateCard: { backgroundColor: '#1A2432', padding: 20, borderRadius: 15, gap: 10, marginBottom: 10 },
  rate: { color: '#D7BB7B', fontSize: 21, fontWeight: '700' },
  inputRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#1A2432', borderWidth: 1, borderColor: '#53697F', borderRadius: 12, paddingHorizontal: 16 },
  input: { flex: 1, color: '#FFF', fontSize: 22, paddingVertical: 16 },
  presets: { flexDirection: 'row', gap: 8 },
  preset: { flex: 1, backgroundColor: '#253346', paddingVertical: 12, alignItems: 'center', borderRadius: 9 },
  presetText: { color: '#C2D2E3', fontSize: 12 },
  error: { color: '#FDA4AF', fontSize: 13 },
});
