import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  background: { flex: 1, backgroundColor: '#12151D' },
  shade: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(8, 12, 20, 0.78)' },
  content: { flexGrow: 1, alignItems: 'center', paddingHorizontal: 22, paddingTop: 30, paddingBottom: 32 },
  eyebrow: { color: '#D5B87F', fontSize: 11, letterSpacing: 4, fontWeight: '700' },
  title: { color: '#FFF5E3', fontSize: 30, fontWeight: '800', marginTop: 10 },
  subtitle: { color: '#CCC8C0', fontSize: 14, marginTop: 10 },
  previewNote: { color: '#A7AFBA', fontSize: 11, marginTop: 12 },
  stage: { flex: 1, minHeight: 340, alignItems: 'center', justifyContent: 'center', paddingVertical: 28 },
  cardFrame: { width: 171, height: 240, shadowColor: '#EAC681', shadowOpacity: 0.7, shadowRadius: 22, shadowOffset: { width: 0, height: 0 }, elevation: 10 },
  heroCard: { width: '100%', height: '100%', resizeMode: 'contain' },
  level: { position: 'absolute', bottom: 26, alignSelf: 'center', fontWeight: '700', color: '#FFFFFF', fontSize: 18 },
  flash: { position: 'absolute', top: 48, alignSelf: 'center', color: '#FFE7AA', fontSize: 100 },
  emptyCard: { width: 171, height: 240, borderWidth: 2, borderStyle: 'dashed', borderColor: '#9E895E', borderRadius: 12, backgroundColor: '#192432', alignItems: 'center', justifyContent: 'center', gap: 18 },
  emptyIcon: { color: '#EAC681', fontSize: 48 },
  emptyText: { color: '#DCCDB0', textAlign: 'center', lineHeight: 24 },
  stageText: { color: '#E4D9C4', fontSize: 14, marginTop: 24, textAlign: 'center', lineHeight: 22 },
  resultTitle: { color: '#F5D390', fontSize: 26, fontWeight: '800', marginBottom: 18 },
  failure: { color: '#EDAB9F' },
  picker: { flexDirection: 'row', gap: 8, width: '100%', maxWidth: 420 },
  option: { flex: 1, padding: 9, borderWidth: 1, borderColor: '#3A4655', backgroundColor: '#192432', borderRadius: 12, alignItems: 'center', gap: 7 },
  selectedOption: { borderColor: '#EAC681', backgroundColor: '#34332E' },
  thumbnail: { width: 48, height: 68, resizeMode: 'contain' },
  optionName: { color: '#E3DFD6', fontSize: 11, textAlign: 'center' },
  optionLevel: { color: '#EAC681', fontWeight: '700', fontSize: 13 },
  actions: { width: '100%', maxWidth: 420, gap: 12, marginTop: 22 },
  hint: { color: '#C6C6CB', fontSize: 11, textAlign: 'center', lineHeight: 18 },
  error: { color: '#F1C6AD', textAlign: 'center', fontSize: 13, lineHeight: 20 },
  button: { backgroundColor: '#EAC681', minHeight: 58, borderRadius: 16, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 10, padding: 14 },
  buttonText: { color: '#292015', fontSize: 18, fontWeight: '800' },
  disabled: { opacity: 0.4 },
});
