import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  background: { flex: 1, backgroundColor: '#12151D' },
  shade: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(8, 12, 20, 0.78)',
  },
  content: {
    flexGrow: 1,
    alignItems: 'center',
    paddingHorizontal: 22,
    paddingTop: 30,
    paddingBottom: 32,
  },
  eyebrow: {
    color: '#D5B87F',
    fontSize: 11,
    letterSpacing: 4,
    fontWeight: '700',
  },
  title: {
    color: '#FFF5E3',
    fontSize: 30,
    fontWeight: '800',
    marginTop: 10,
  },
  subtitle: { color: '#CCC8C0', fontSize: 14, marginTop: 10 },
  previewNote: { color: '#A7AFBA', fontSize: 11, marginTop: 12 },
  stage: {
    flex: 1,
    minHeight: 390,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 28,
  },
  strikeScene: {
    width: 245,
    minHeight: 264,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  cardGlow: {
    shadowColor: '#EAC681',
    shadowOpacity: 0.7,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 0 },
    elevation: 10,
  },
  cardFrame: {
    width: 171,
    aspectRatio: 512 / 720,
    borderWidth: 3,
    borderRadius: 15,
    overflow: 'hidden',
    backgroundColor: '#151C2C',
  },
  failedCardFrame: { backgroundColor: '#686D76' },
  heroCard: { width: '100%', height: '100%' },
  failedImageGrayscale: {
    filter: 'grayscale(1)',
    opacity: 0.62,
  },
  failedImageIos: { opacity: 0.28 },
  failedShade: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(92, 98, 108, 0.48)',
  },
  gradeBadge: {
    position: 'absolute',
    top: 10,
    right: 10,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 9,
  },
  gradeText: {
    color: '#20242B',
    fontSize: 11,
    fontWeight: '800',
  },
  heroLevelBadge: {
    position: 'absolute',
    left: 10,
    bottom: 10,
    backgroundColor: 'rgba(8, 12, 20, 0.86)',
    borderColor: '#EAC681',
    borderWidth: 1,
    borderRadius: 9,
    paddingHorizontal: 11,
    paddingVertical: 6,
  },
  heroLevelText: {
    color: '#F5D390',
    fontSize: 15,
    fontWeight: '800',
  },
  hammer: {
    position: 'absolute',
    top: -8,
    right: 17,
    zIndex: 5,
  },
  hammerIcon: { fontSize: 66 },
  impactFlash: {
    position: 'absolute',
    top: 55,
    right: 54,
    zIndex: 4,
  },
  impactIcon: {
    color: '#FFF0B3',
    fontSize: 60,
    textShadowColor: '#FFB347',
    textShadowRadius: 14,
  },
  emptyCard: {
    width: 171,
    height: 240,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: '#9E895E',
    borderRadius: 12,
    backgroundColor: '#192432',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 18,
  },
  emptyIcon: { color: '#EAC681', fontSize: 48 },
  emptyText: { color: '#DCCDB0', textAlign: 'center', lineHeight: 24 },
  stageText: {
    color: '#E4D9C4',
    fontSize: 14,
    marginTop: 24,
    textAlign: 'center',
    lineHeight: 22,
  },
  resultTitle: {
    color: '#F5D390',
    fontSize: 26,
    fontWeight: '800',
    marginBottom: 18,
  },
  failure: { color: '#EDAB9F' },
  actions: {
    width: '100%',
    maxWidth: 420,
    gap: 12,
    marginTop: 22,
  },
  hint: {
    color: '#C6C6CB',
    fontSize: 11,
    textAlign: 'center',
    lineHeight: 18,
  },
  error: {
    color: '#F1C6AD',
    textAlign: 'center',
    fontSize: 13,
    lineHeight: 20,
  },
  button: {
    backgroundColor: '#EAC681',
    minHeight: 58,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 10,
    padding: 14,
  },
  buttonText: { color: '#292015', fontSize: 18, fontWeight: '800' },
  disabled: { opacity: 0.4 },
});
