import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  background: { flex: 1, backgroundColor: '#12151D' },
  shade: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(8, 12, 20, 0.78)',
  },
  content: {
    flexGrow: 1,
    alignItems: 'center',
    paddingHorizontal: 22,
    paddingTop: 30,
    paddingBottom: 32,
  },
  eyebrow: {
    color: '#D5B87F',
    fontSize: 11,
    letterSpacing: 4,
    fontWeight: '700',
  },
  title: {
    color: '#FFF5E3',
    fontSize: 30,
    fontWeight: '800',
    marginTop: 10,
  },
  subtitle: { color: '#CCC8C0', fontSize: 14, marginTop: 10 },
  previewNote: { color: '#A7AFBA', fontSize: 11, marginTop: 12 },
  stage: {
    flex: 1,
    minHeight: 390,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 28,
  },
  strikeScene: {
    width: 245,
    minHeight: 264,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  cardGlow: {
    shadowColor: '#EAC681',
    shadowOpacity: 0.7,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 0 },
    elevation: 10,
  },
  cardFrame: {
    width: 171,
    aspectRatio: 512 / 720,
    borderWidth: 3,
    borderRadius: 15,
    overflow: 'hidden',
    backgroundColor: '#151C2C',
  },
  failedCardFrame: { backgroundColor: '#686D76' },
  heroCard: { width: '100%', height: '100%' },
  failedImageGrayscale: {
    filter: 'grayscale(1)',
    opacity: 0.62,
  },
  failedImageIos: { opacity: 0.28 },
  failedShade: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(92, 98, 108, 0.48)',
  },
  gradeBadge: {
    position: 'absolute',
    top: 10,
    right: 10,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 9,
  },
  gradeText: {
    color: '#20242B',
    fontSize: 11,
    fontWeight: '800',
  },
  heroLevelBadge: {
    position: 'absolute',
    left: 10,
    bottom: 10,
    backgroundColor: 'rgba(8, 12, 20, 0.86)',
    borderColor: '#EAC681',
    borderWidth: 1,
    borderRadius: 9,
    paddingHorizontal: 11,
    paddingVertical: 6,
  },
  heroLevelText: {
    color: '#F5D390',
    fontSize: 15,
    fontWeight: '800',
  },
  strikeOverlay: {
    position: 'absolute',
    top: -10,
    right: -10,
    bottom: -10,
    left: -10,
    zIndex: 100,
    overflow: 'hidden',
    backgroundColor: '#080A0D',
  },
  strikeBackdrop: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
    opacity: 0.46,
    transform: [{ scale: 1.18 }],
  },
  strikeBackdropShade: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(5, 7, 10, 0.67)',
  },
  forgeVignette: {
    ...StyleSheet.absoluteFillObject,
    borderWidth: 34,
    borderColor: 'rgba(0, 0, 0, 0.38)',
  },
  forgeCaption: {
    position: 'absolute',
    top: 60,
    alignSelf: 'center',
    color: '#D5B87F',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 4,
    zIndex: 3,
  },
  fullForgeScene: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fullHammer: {
    position: 'absolute',
    top: '18%',
    right: '8%',
    zIndex: 5,
  },
  fullHammerIcon: {
    fontSize: 138,
    textShadowColor: 'rgba(0, 0, 0, 0.9)',
    textShadowRadius: 18,
    textShadowOffset: { width: 7, height: 12 },
  },
  anvil: {
    position: 'absolute',
    top: '52%',
    width: 270,
    height: 180,
    alignItems: 'center',
  },
  anvilTop: {
    width: 240,
    height: 38,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#9DA1A8',
    backgroundColor: '#555B63',
    transform: [{ skewX: '-9deg' }],
    shadowColor: '#000',
    shadowOpacity: 0.9,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 10 },
    elevation: 16,
  },
  heatedMetal: {
    position: 'absolute',
    top: 8,
    width: 150,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#FF7138',
    borderColor: '#FFD07A',
    borderWidth: 2,
    shadowColor: '#FF4D21',
    shadowOpacity: 1,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 0 },
    elevation: 20,
    zIndex: 2,
  },
  anvilStem: {
    width: 92,
    height: 76,
    backgroundColor: '#454A51',
    borderLeftWidth: 8,
    borderRightWidth: 8,
    borderColor: '#30343A',
  },
  anvilBase: {
    width: 180,
    height: 28,
    borderRadius: 7,
    borderWidth: 2,
    borderColor: '#717780',
    backgroundColor: '#383D44',
  },
  fullImpact: {
    position: 'absolute',
    top: '43%',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 7,
  },
  sparkText: {
    color: '#FFF2B0',
    fontSize: 54,
    letterSpacing: 8,
    textShadowColor: '#FF7A24',
    textShadowRadius: 22,
  },
  bangText: {
    color: '#FFF4D0',
    fontSize: 58,
    fontWeight: '900',
    marginTop: -12,
    textShadowColor: '#FF5A24',
    textShadowRadius: 20,
  },
  strikeProgress: {
    position: 'absolute',
    right: 0,
    bottom: 72,
    left: 0,
    color: '#F4E6CC',
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 1,
    textAlign: 'center',
    zIndex: 4,
  },
  emptyCard: {
    width: 171,
    height: 240,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: '#9E895E',
    borderRadius: 12,
    backgroundColor: '#192432',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 18,
  },
  emptyIcon: { color: '#EAC681', fontSize: 48 },
  emptyText: { color: '#DCCDB0', textAlign: 'center', lineHeight: 24 },
  stageText: {
    color: '#E4D9C4',
    fontSize: 14,
    marginTop: 24,
    textAlign: 'center',
    lineHeight: 22,
  },
  resultTitle: {
    color: '#F5D390',
    fontSize: 26,
    fontWeight: '800',
    marginBottom: 18,
  },
  failure: { color: '#EDAB9F' },
  actions: {
    width: '100%',
    maxWidth: 420,
    gap: 12,
    marginTop: 22,
  },
  hint: {
    color: '#C6C6CB',
    fontSize: 11,
    textAlign: 'center',
    lineHeight: 18,
  },
  error: {
    color: '#F1C6AD',
    textAlign: 'center',
    fontSize: 13,
    lineHeight: 20,
  },
  button: {
    backgroundColor: '#EAC681',
    minHeight: 58,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 10,
    padding: 14,
  },
  buttonText: { color: '#292015', fontSize: 18, fontWeight: '800' },
  disabled: { opacity: 0.4 },
});
