-- Source of truth: public/docs/데이터베이스_구조.md
-- Rules version: card-database-rules-v1

CREATE TABLE public.users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  toss_user_id text NOT NULL UNIQUE
);

CREATE TABLE public.cards (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  element text NOT NULL
    CHECK (element IN ('EARTH', 'WATER', 'WIND', 'FIRE', 'LIGHT', 'DARK')),
  rarity text NOT NULL
    CHECK (rarity IN ('NORMAL', 'MAGIC', 'RARE', 'SUPER_RARE', 'UNIQUE', 'LEGENDARY')),
  image_path text
);

CREATE TABLE public.user_cards (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  card_id bigint NOT NULL REFERENCES public.cards(id) ON DELETE RESTRICT,
  enhancement_level integer NOT NULL DEFAULT 0
    CHECK (enhancement_level >= 0)
);

CREATE INDEX user_cards_user_id_id_idx
  ON public.user_cards(user_id, id);

-- 앱은 테이블을 직접 읽거나 수정하지 않습니다. 이후 Edge Function이 검증된
-- 서버 권한으로 접근하며, anon/authenticated용 정책은 의도적으로 만들지 않습니다.
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_cards ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.users FROM anon, authenticated;
REVOKE ALL ON TABLE public.cards FROM anon, authenticated;
REVOKE ALL ON TABLE public.user_cards FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.users_id_seq FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.cards_id_seq FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.user_cards_id_seq FROM anon, authenticated;

INSERT INTO public.cards (id, name, element, rarity, image_path) VALUES
  (1, '대지의 수호자', 'EARTH', 'NORMAL', '/cards/earth_guardian.png'),
  (2, '물결의 정령', 'WATER', 'NORMAL', '/cards/wave_spirit.png'),
  (3, '바람의 궁수', 'WIND', 'NORMAL', '/cards/wind_archer.png'),
  (4, '불꽃 기사', 'FIRE', 'NORMAL', '/cards/flame_knight.png'),
  (5, '빛의 사제', 'LIGHT', 'NORMAL', '/cards/priest_of_light.png'),
  (6, '그림자 도적', 'DARK', 'NORMAL', '/cards/shadow_rogue.png'),
  (7, '바위 주술사', 'EARTH', 'MAGIC', '/cards/rock_shaman.png'),
  (8, '심해의 파도', 'WATER', 'MAGIC', '/cards/deep_sea_wave.png'),
  (9, '회오리 무희', 'WIND', 'MAGIC', '/cards/whirlwind_dancer.png'),
  (10, '잿불 마법사', 'FIRE', 'MAGIC', '/cards/ember_mage.png'),
  (11, '여명의 기사', 'LIGHT', 'MAGIC', '/cards/dawn_knight.png'),
  (12, '밤안개 추적자', 'DARK', 'MAGIC', '/cards/night_mist_tracker.png'),
  (13, '강철뿌리 거인', 'EARTH', 'RARE', '/cards/steelroot_giant.png'),
  (14, '서리의 마녀', 'WATER', 'RARE', '/cards/frost_witch.png'),
  (15, '질풍의 정령', 'WIND', 'RARE', '/cards/gale_spirit.png'),
  (16, '홍염의 검사', 'FIRE', 'RARE', '/cards/crimson_swordsman.png'),
  (17, '광휘의 성기사', 'LIGHT', 'RARE', '/cards/radiant_paladin.png'),
  (18, '칠흑의 암살자', 'DARK', 'RARE', '/cards/pitch_black_assassin.png'),
  (19, '지진의 거신', 'EARTH', 'SUPER_RARE', '/cards/earthquake_colossus.png'),
  (20, '해일의 지배자', 'WATER', 'SUPER_RARE', '/cards/tidal_ruler.png'),
  (21, '폭풍 그리핀', 'WIND', 'SUPER_RARE', '/cards/storm_griffin.png'),
  (22, '불꽃 드래곤', 'FIRE', 'SUPER_RARE', '/cards/flame_dragon.png'),
  (23, '천상의 집행자', 'LIGHT', 'SUPER_RARE', '/cards/celestial_executor.png'),
  (24, '망령의 지휘관', 'DARK', 'SUPER_RARE', '/cards/spectral_commander.png'),
  (25, '태산의 제왕', 'EARTH', 'UNIQUE', '/cards/mountain_emperor.png'),
  (26, '영원의 빙룡', 'WATER', 'UNIQUE', '/cards/eternal_ice_dragon.png'),
  (27, '창공의 군주', 'WIND', 'UNIQUE', '/cards/sky_sovereign.png'),
  (28, '불멸의 불사조', 'FIRE', 'UNIQUE', '/cards/immortal_phoenix.png'),
  (29, '찬란한 심판', 'LIGHT', 'UNIQUE', '/cards/radiant_judgment.png'),
  (30, '파멸의 사신', 'DARK', 'UNIQUE', '/cards/doom_reaper.png'),
  (31, '태초의 대지신', 'EARTH', 'LEGENDARY', '/cards/primordial_earth_god.png'),
  (32, '만해의 용왕', 'WATER', 'LEGENDARY', '/cards/dragon_king_of_all_seas.png'),
  (33, '천공의 폭풍신', 'WIND', 'LEGENDARY', '/cards/heavenly_storm_god.png'),
  (34, '종말의 염룡', 'FIRE', 'LEGENDARY', '/cards/apocalypse_flame_dragon.png'),
  (35, '창세의 광휘', 'LIGHT', 'LEGENDARY', '/cards/genesis_radiance.png'),
  (36, '심연의 군주', 'DARK', 'LEGENDARY', '/cards/abyss_lord.png');

SELECT setval(
  pg_get_serial_sequence('public.cards', 'id'),
  (SELECT max(id) FROM public.cards)
);
