-- Apps in Toss membership sessions for the bigint user model.

ALTER TABLE public.users
  ADD COLUMN display_name text NOT NULL DEFAULT '모험가',
  ADD COLUMN account_status text NOT NULL DEFAULT 'ACTIVE'
    CHECK (account_status IN ('ACTIVE', 'SUSPENDED', 'WITHDRAWN')),
  ADD COLUMN created_at timestamptz NOT NULL DEFAULT now(),
  ADD COLUMN last_signed_in_at timestamptz NOT NULL DEFAULT now();

CREATE TABLE public.user_sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  token_digest text NOT NULL UNIQUE,
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX user_sessions_active_token_idx
  ON public.user_sessions(token_digest, expires_at)
  WHERE revoked_at IS NULL;

ALTER TABLE public.user_sessions ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.user_sessions FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.user_sessions_id_seq FROM anon, authenticated;

CREATE OR REPLACE FUNCTION public.initialize_user_session(
  p_toss_user_digest text,
  p_token_digest text,
  p_expires_at timestamptz
)
RETURNS TABLE (
  user_id bigint,
  display_name text,
  account_status text,
  created_at timestamptz,
  last_signed_in_at timestamptz,
  is_new_user boolean
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_user_id bigint;
  v_is_new boolean := false;
BEGIN
  IF length(p_toss_user_digest) <> 64 OR length(p_token_digest) <> 64 THEN
    RAISE EXCEPTION 'INVALID_DIGEST';
  END IF;
  IF p_expires_at <= now() THEN
    RAISE EXCEPTION 'INVALID_SESSION_EXPIRY';
  END IF;

  INSERT INTO public.users (toss_user_id)
  VALUES (p_toss_user_digest)
  ON CONFLICT (toss_user_id) DO NOTHING
  RETURNING id INTO v_user_id;

  IF v_user_id IS NOT NULL THEN
    v_is_new := true;
  ELSE
    SELECT id INTO v_user_id
    FROM public.users
    WHERE toss_user_id = p_toss_user_digest
    FOR UPDATE;
  END IF;

  UPDATE public.users
  SET last_signed_in_at = now()
  WHERE id = v_user_id;

  INSERT INTO public.user_sessions (user_id, token_digest, expires_at)
  VALUES (v_user_id, p_token_digest, p_expires_at);

  RETURN QUERY
  SELECT u.id, u.display_name, u.account_status, u.created_at,
         u.last_signed_in_at, v_is_new
  FROM public.users AS u
  WHERE u.id = v_user_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.find_user_by_session(p_token_digest text)
RETURNS TABLE (
  user_id bigint,
  display_name text,
  account_status text,
  created_at timestamptz,
  last_signed_in_at timestamptz
)
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = ''
AS $$
  SELECT u.id, u.display_name, u.account_status, u.created_at,
         u.last_signed_in_at
  FROM public.user_sessions AS s
  JOIN public.users AS u ON u.id = s.user_id
  WHERE s.token_digest = p_token_digest
    AND s.revoked_at IS NULL
    AND s.expires_at > now()
    AND u.account_status = 'ACTIVE'
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.update_user_display_name(
  p_token_digest text,
  p_display_name text
)
RETURNS TABLE (
  user_id bigint,
  display_name text,
  account_status text,
  created_at timestamptz,
  last_signed_in_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_user_id bigint;
BEGIN
  SELECT s.user_id INTO v_user_id
  FROM public.user_sessions AS s
  JOIN public.users AS u ON u.id = s.user_id
  WHERE s.token_digest = p_token_digest
    AND s.revoked_at IS NULL
    AND s.expires_at > now()
    AND u.account_status = 'ACTIVE'
  FOR UPDATE OF u;

  IF v_user_id IS NULL THEN
    RETURN;
  END IF;

  UPDATE public.users SET display_name = p_display_name WHERE id = v_user_id;
  RETURN QUERY
  SELECT u.id, u.display_name, u.account_status, u.created_at,
         u.last_signed_in_at
  FROM public.users AS u WHERE u.id = v_user_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.revoke_user_session(p_token_digest text)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_updated integer;
BEGIN
  UPDATE public.user_sessions
  SET revoked_at = now()
  WHERE token_digest = p_token_digest
    AND revoked_at IS NULL
    AND expires_at > now();
  GET DIAGNOSTICS v_updated = ROW_COUNT;
  RETURN v_updated = 1;
END;
$$;

REVOKE ALL ON FUNCTION public.initialize_user_session(text, text, timestamptz) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.find_user_by_session(text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.update_user_display_name(text, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.revoke_user_session(text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.initialize_user_session(text, text, timestamptz) TO service_role;
GRANT EXECUTE ON FUNCTION public.find_user_by_session(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.update_user_display_name(text, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.revoke_user_session(text) TO service_role;
