import type { Route as _IndexRoute } from '../pages/';
/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import type { Route as _AboutRoute } from '../pages/about';
import type { Route as _CardDetailRoute } from '../pages/card-detail';
import type { Route as _CardsRoute } from '../pages/cards';
import type { Route as _CollectionRoute } from '../pages/collection';
import type { Route as _ExchangeRoute } from '../pages/exchange';
import type { Route as _ForgeRoute } from '../pages/forge';
import type { Route as _PacksRoute } from '../pages/packs';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/about': (typeof _AboutRoute)['_inputType'];
    '/card-detail': (typeof _CardDetailRoute)['_inputType'];
    '/cards': (typeof _CardsRoute)['_inputType'];
    '/collection': (typeof _CollectionRoute)['_inputType'];
    '/exchange': (typeof _ExchangeRoute)['_inputType'];
    '/forge': (typeof _ForgeRoute)['_inputType'];
    '/packs': (typeof _PacksRoute)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/about': (typeof _AboutRoute)['_outputType'];
    '/card-detail': (typeof _CardDetailRoute)['_outputType'];
    '/cards': (typeof _CardsRoute)['_outputType'];
    '/collection': (typeof _CollectionRoute)['_outputType'];
    '/exchange': (typeof _ExchangeRoute)['_outputType'];
    '/forge': (typeof _ForgeRoute)['_outputType'];
    '/packs': (typeof _PacksRoute)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
  }
}
